apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: aadpodidentity-kube-eclinic-agentpool
spec:
  type: 0
  ResourceID: /subscriptions/eexxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/resourceGroups/MC_rg-eClinic_kube-eClinic_southeastasia/providers/Microsoft.ManagedIdentity/userAssignedIdentities/kube-eClinic-agentpool
  ClientID: 7c20xxxxx-xxxx-xxxc-xxxx-xxxxxxxxxxx
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: kube-eclinic-agentpool-identity-binding
spec:
  AzureIdentity: aadpodidentity-kube-eclinic-agentpool
  Selector: aadpodidentity-kube-eclinic-agentpool