apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-svc-pr
  namespace: eclinic
  labels:
    app: api-pr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-pr
  template:
    metadata:
      labels:
        app: api-pr
    spec:
      containers:
        - name: api-pr
          image: acreclinic.azurecr.io/patientregistration:patientregistration-0.0.1
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /api/pr/health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
              httpGet:
                path: /api/pr/health
                port: 3000
              initialDelaySeconds: 3
              periodSeconds: 3